# Generated by Django 3.1.5 on 2021-01-11 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'Username in use'}, help_text='Maximum 20 characters, only letters and numbers', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters and numbers allowed', regex='[aA0-zZ9]')], verbose_name='username'),
        ),
    ]
