# Generated by Django 3.1.5 on 2021-01-11 01:44

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date of last modification', verbose_name='last modified')),
                ('name', models.CharField(error_messages={'unique': 'Ingredient already exists'}, help_text='Maximum 25 characters, only letters and numbers', max_length=25, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters and numbers allowed', regex='[aA0-zZ9]')])),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IngredientComposition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=21)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date of creation', verbose_name='created at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date of last modification', verbose_name='last modified')),
                ('name', models.CharField(help_text='Maximum 50 characters, only letters and numbers', max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters and numbers allowed', regex='[aA0-zZ9]')])),
                ('ingredients', models.ManyToManyField(through='recipes.IngredientComposition', to='recipes.Ingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.AddField(
            model_name='ingredientcomposition',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe'),
        ),
    ]
